/**
 * CloudSentinel — synthetic CloudTrail activity generator.
 *
 * Produces a realistic stream of AWS API-call records for a fictional account,
 * plus a separate answer key describing the attacks deliberately hidden inside
 * it. This is the data source for the ML anomaly layer.
 *
 *   npm run logs:gen                       write the default 30-day log
 *   npm run logs:gen -- --days 7           a shorter log
 *   npm run logs:gen -- --seed other       a different (still reproducible) run
 *   npm run logs:gen -- --no-attacks       clean baseline traffic only
 *
 * Where it sits in the architecture: the head of stage three. Everything it
 * emits conforms to lib/types/cloudtrail.ts, which is the contract the Python
 * layer parses against.
 *
 *   [ this file ] --> fixtures/cloudtrail.json ------> ml/features.py --> ml/detect.py
 *                 \                                                          |
 *                  -> fixtures/cloudtrail-labels.json --> ml/evaluate.py <---+
 *
 * ---------------------------------------------------------------------------
 * Why synthesize the data at all
 * ---------------------------------------------------------------------------
 *
 * The honest answer is that there is no alternative that is both legal and
 * useful. Real CloudTrail logs are among the most sensitive artefacts an AWS
 * account produces — they record who did what, from which address, at what
 * hour — so no organisation publishes them, and none should. The public
 * intrusion-detection datasets that do exist are network traces, not
 * cloud-control-plane traces, and LocalStack does not emit a usable trail.
 *
 * Synthetic data buys something a real trail could not, though, and it is worth
 * being clear about it: **ground truth**. In a real log nobody knows with
 * certainty which events were an attack, so "the model flagged 4 things" is
 * unfalsifiable. Here the attacks are placed on purpose, so precision and
 * recall are actually computable and a claim like "the Isolation Forest beat
 * the statistical baseline" can be checked rather than asserted.
 *
 * The cost, which must not be glossed over: a model evaluated only on data
 * generated by these rules is partly being tested on the generator's
 * assumptions. If the generator believes analysts never work at night, the
 * detector will look excellent at spotting night-time analysts and will say
 * nothing about how it behaves in an account where half the team is in Berlin.
 * The numbers in ml/evaluate.py are therefore a demonstration that the pipeline
 * works end to end, not a claim about real-world accuracy. That distinction is
 * repeated in the evaluation output itself so nobody quotes the figure without
 * the caveat.
 *
 * ---------------------------------------------------------------------------
 * The control group
 * ---------------------------------------------------------------------------
 *
 * Two principals below exist to be *boring in a difficult way*, mirroring the
 * compliant buckets that scripts/seed-localstack.ts uses as a false-positive
 * baseline for the rule engine:
 *
 *   - `backup-service` is an automated role running 24/7 with a large nightly
 *     batch spike. It is active at 3am and it makes hundreds of calls an hour.
 *     A naive detector keyed on "night-time activity" or "high volume" flags it
 *     every single day.
 *   - `dave-admin` performs IAM writes — `AttachUserPolicy`, `CreateAccessKey`
 *     — as his ordinary job. A detector keyed on "sensitive IAM action" flags
 *     him constantly.
 *
 * Both must come out clean. That is the entire argument for baselining
 * per-principal rather than account-wide: the *same* action is unremarkable
 * from Dave and alarming from an analyst who has never called IAM in his life.
 * A model that cannot express that is a model that either misses the real
 * escalation or drowns the account in false positives, and either failure gets
 * the tool switched off.
 *
 * SECURITY: everything here is fabricated. The account id is the reserved
 * documentation placeholder, and every address comes from the RFC 5737 example
 * ranges (192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24), which route nowhere.
 * That is deliberate for a public repository: a plausible-looking invented IP
 * usually belongs to somebody real, and committing a file that appears to
 * accuse a genuine address of credential theft is a concrete harm even when the
 * surrounding data is fake. The names are equally fictional and match the
 * `cloudsentinel-*` fixtures used elsewhere in the project.
 */

import type {
  ActivityLabels,
  ActivityLog,
  ActivityLogMetadata,
  AnomalyLabel,
  CloudTrailEvent,
} from "../types/cloudtrail.ts";
import { createRandom, type Random } from "../util/random.ts";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * The fictional AWS account every generated event belongs to.
 *
 * `123456789012` is the placeholder AWS itself uses throughout its
 * documentation, so it is universally recognised as "not a real account" and
 * cannot collide with anyone's.
 */
const ACCOUNT_ID = "123456789012";

/** CloudTrail's current schema version, carried for realism. */
const EVENT_VERSION = "1.11";

/** Milliseconds in one hour, used throughout the time arithmetic. */
const HOUR_MS = 60 * 60 * 1000;

/** Milliseconds in one day. */
const DAY_MS = 24 * HOUR_MS;

/**
 * Default start of the generated window: midnight UTC on Monday 1 June 2026.
 *
 * A Monday start matters because the weekday/weekend rhythm is one of the
 * behavioural patterns being modelled, and a window that began mid-weekend
 * would open with two unrepresentative days. Midnight UTC keeps every day
 * boundary aligned with the hour buckets the feature extractor uses.
 */
const DEFAULT_START_TIME = "2026-06-01T00:00:00.000Z";

/** Default length of the generated window, in days. */
const DEFAULT_DAYS = 30;

/** Default PRNG seed. Changing this regenerates every value in the log. */
const DEFAULT_SEED = "cloudsentinel";

// ---------------------------------------------------------------------------
// Action vocabulary
// ---------------------------------------------------------------------------

/**
 * One kind of API call a principal might make, with how often it makes it.
 *
 * Actions are drawn by weight rather than uniformly, because real activity is
 * heavily skewed: a principal that reads objects makes far more `GetObject`
 * calls than `ListBuckets` calls. Uniform selection would give every principal
 * an unnaturally flat action distribution, and the "distinct actions this hour"
 * feature would then carry no information — every hour would look the same.
 */
interface WeightedAction {
  /** Relative likelihood. Weights need not sum to anything in particular. */
  weight: number;

  /** The service endpoint, e.g. `"s3.amazonaws.com"`. */
  eventSource: string;

  /** The API action name, e.g. `"GetObject"`. */
  eventName: string;

  /** Whether the call only reads state. Drives the write/read ratio feature. */
  readOnly: boolean;

  /** `"Data"` for object-level calls, `"Management"` for control-plane calls. */
  eventCategory: "Management" | "Data";

  /**
   * Builds the recorded request parameters for one call.
   *
   * A function rather than a fixed object so each call can vary — different
   * object keys, different instance ids — which is what makes the
   * "distinct resources touched" signal in the exfiltration scenario possible.
   *
   * @param random - the principal's generator. Drawing from it here advances
   *   the same stream the rest of the principal's events use, which is fine and
   *   deterministic, but means reordering these calls changes the output.
   * @returns the parameters, or `null` for actions that take none.
   */
  parameters?: (random: Random) => Record<string, string | number | boolean>;
}

/**
 * S3 read traffic — the bulk of what a data analyst does.
 *
 * The object keys are drawn from a wide synthetic keyspace so that a normal
 * hour touches a handful of distinct objects and the exfiltration scenario
 * touches hundreds. That contrast is the feature the exfiltration detector
 * relies on; without varied keys a volume spike and a retry loop would be
 * indistinguishable.
 */
const S3_READ_ACTIONS: WeightedAction[] = [
  {
    weight: 60,
    eventSource: "s3.amazonaws.com",
    eventName: "GetObject",
    readOnly: true,
    eventCategory: "Data",
    parameters: (random) => ({
      bucketName: random.pick([
        "cloudsentinel-private-logs",
        "cloudsentinel-analytics",
        "cloudsentinel-reports",
      ]),
      key: `datasets/${random.int(2024, 2026)}/part-${random.int(1, 9999)}.parquet`,
    }),
  },
  {
    weight: 12,
    eventSource: "s3.amazonaws.com",
    eventName: "ListObjectsV2",
    readOnly: true,
    eventCategory: "Data",
    parameters: (random) => ({
      bucketName: random.pick([
        "cloudsentinel-analytics",
        "cloudsentinel-reports",
      ]),
      prefix: `datasets/${random.int(2024, 2026)}/`,
    }),
  },
  {
    weight: 4,
    eventSource: "s3.amazonaws.com",
    eventName: "HeadObject",
    readOnly: true,
    eventCategory: "Data",
    parameters: (random) => ({
      bucketName: "cloudsentinel-analytics",
      key: `datasets/2026/part-${random.int(1, 9999)}.parquet`,
    }),
  },
  {
    weight: 2,
    eventSource: "s3.amazonaws.com",
    eventName: "ListBuckets",
    readOnly: true,
    eventCategory: "Management",
  },
];

/** S3 write traffic — what an automated backup or a deploy pipeline does. */
const S3_WRITE_ACTIONS: WeightedAction[] = [
  {
    weight: 50,
    eventSource: "s3.amazonaws.com",
    eventName: "PutObject",
    readOnly: false,
    eventCategory: "Data",
    parameters: (random) => ({
      bucketName: "cloudsentinel-private-logs",
      key: `backups/${random.int(2024, 2026)}/snapshot-${random.int(1, 9999)}.tar.gz`,
    }),
  },
  {
    weight: 10,
    eventSource: "s3.amazonaws.com",
    eventName: "CompleteMultipartUpload",
    readOnly: false,
    eventCategory: "Data",
    parameters: (random) => ({
      bucketName: "cloudsentinel-private-logs",
      key: `backups/2026/snapshot-${random.int(1, 9999)}.tar.gz`,
    }),
  },
  {
    weight: 8,
    eventSource: "s3.amazonaws.com",
    eventName: "GetObject",
    readOnly: true,
    eventCategory: "Data",
    parameters: (random) => ({
      bucketName: "cloudsentinel-private-logs",
      key: `backups/2026/manifest-${random.int(1, 200)}.json`,
    }),
  },
];

/** EC2 and infrastructure traffic — a DevOps engineer's normal day. */
const EC2_ACTIONS: WeightedAction[] = [
  {
    weight: 30,
    eventSource: "ec2.amazonaws.com",
    eventName: "DescribeInstances",
    readOnly: true,
    eventCategory: "Management",
  },
  {
    weight: 14,
    eventSource: "ec2.amazonaws.com",
    eventName: "DescribeSecurityGroups",
    readOnly: true,
    eventCategory: "Management",
  },
  {
    weight: 10,
    eventSource: "cloudwatch.amazonaws.com",
    eventName: "GetMetricData",
    readOnly: true,
    eventCategory: "Management",
  },
  {
    weight: 6,
    eventSource: "ec2.amazonaws.com",
    eventName: "DescribeVolumes",
    readOnly: true,
    eventCategory: "Management",
  },
  {
    weight: 4,
    eventSource: "ec2.amazonaws.com",
    eventName: "CreateTags",
    readOnly: false,
    eventCategory: "Management",
    parameters: (random) => ({
      resourceId: `i-0${random.int(100000, 999999)}abcdef`,
    }),
  },
  {
    weight: 3,
    eventSource: "ec2.amazonaws.com",
    eventName: "RunInstances",
    readOnly: false,
    eventCategory: "Management",
    parameters: (random) => ({
      instanceType: random.pick(["t3.micro", "t3.small", "m5.large"]),
    }),
  },
  {
    weight: 2,
    eventSource: "ec2.amazonaws.com",
    eventName: "TerminateInstances",
    readOnly: false,
    eventCategory: "Management",
    parameters: (random) => ({
      instanceId: `i-0${random.int(100000, 999999)}abcdef`,
    }),
  },
];

/**
 * IAM administration — legitimate, routine, and performed only by `dave-admin`.
 *
 * These are the exact action names the privilege-escalation scenario uses. That
 * overlap is the point: the action alone proves nothing, so a detector that
 * pattern-matches on `AttachUserPolicy` will flag Dave every week and be turned
 * off long before it ever sees a real escalation. Only the pairing of the
 * action with a principal that has never performed it carries signal.
 */
const IAM_ADMIN_ACTIONS: WeightedAction[] = [
  {
    weight: 20,
    eventSource: "iam.amazonaws.com",
    eventName: "ListUsers",
    readOnly: true,
    eventCategory: "Management",
  },
  {
    weight: 12,
    eventSource: "iam.amazonaws.com",
    eventName: "GetUser",
    readOnly: true,
    eventCategory: "Management",
    parameters: (random) => ({
      userName: random.pick(["alice-analyst", "bob-devops", "carol-finance"]),
    }),
  },
  {
    weight: 10,
    eventSource: "iam.amazonaws.com",
    eventName: "ListAttachedUserPolicies",
    readOnly: true,
    eventCategory: "Management",
    parameters: (random) => ({
      userName: random.pick(["alice-analyst", "bob-devops"]),
    }),
  },
  {
    weight: 6,
    eventSource: "iam.amazonaws.com",
    eventName: "AttachUserPolicy",
    readOnly: false,
    eventCategory: "Management",
    parameters: (random) => ({
      userName: random.pick(["alice-analyst", "bob-devops", "carol-finance"]),
      policyArn: "arn:aws:iam::aws:policy/ReadOnlyAccess",
    }),
  },
  {
    weight: 4,
    eventSource: "iam.amazonaws.com",
    eventName: "CreateAccessKey",
    readOnly: false,
    eventCategory: "Management",
    parameters: (random) => ({
      userName: random.pick(["bob-devops", "carol-finance"]),
    }),
  },
  {
    weight: 4,
    eventSource: "iam.amazonaws.com",
    eventName: "TagUser",
    readOnly: false,
    eventCategory: "Management",
    parameters: () => ({ userName: "alice-analyst" }),
  },
];

/** Console and identity traffic that most human principals produce daily. */
const CONSOLE_ACTIONS: WeightedAction[] = [
  {
    weight: 10,
    eventSource: "signin.amazonaws.com",
    eventName: "ConsoleLogin",
    readOnly: false,
    eventCategory: "Management",
  },
  {
    weight: 8,
    eventSource: "sts.amazonaws.com",
    eventName: "GetCallerIdentity",
    readOnly: true,
    eventCategory: "Management",
  },
];

// ---------------------------------------------------------------------------
// Principal profiles
// ---------------------------------------------------------------------------

/**
 * The behavioural fingerprint of one principal.
 *
 * Everything the generator needs to produce a month of plausible activity for
 * one identity: when it works, where it works from, how much it does, and what
 * kinds of calls it makes.
 *
 * The fields describing *when* are the ones that carry the most weight. Real
 * principals fall into two sharply different populations — humans, who work a
 * local business day and rest at night, and automation, which runs on a
 * schedule and does not care what time it is. Modelling both is necessary
 * because a detector that assumes everything is human flags every backup job,
 * and one that assumes everything is automated notices nothing at all.
 */
export interface PrincipalProfile {
  /** Full ARN — the grouping key for every downstream feature. */
  arn: string;

  /** AWS's opaque principal id, e.g. `AIDA...`. */
  principalId: string;

  /** Which identity variant this is. See lib/types/cloudtrail.ts. */
  type: "IAMUser" | "AssumedRole" | "Root";

  /** IAM user name, for `IAMUser` principals. */
  userName?: string;

  /** Role session name, for `AssumedRole` principals. */
  sessionName?: string;

  /** Plain-language note on the persona, shown in generator output. */
  description: string;

  /**
   * Offset from UTC of the principal's local time, in hours.
   *
   * Stored as an offset rather than a timezone name so that no timezone
   * database is needed and the arithmetic is one addition. Daylight saving is
   * deliberately not modelled: it would shift the working-hours boundary
   * mid-month and make the off-hours feature noisier for reasons that have
   * nothing to do with security. A real deployment would have to handle it.
   */
  utcOffsetHours: number;

  /** First hour of the working day, in the principal's local time (0-23). */
  workStartHourLocal: number;

  /** Last hour of the working day, in local time, inclusive. */
  workEndHourLocal: number;

  /** Whether this principal is normally active on Saturdays and Sundays. */
  worksWeekends: boolean;

  /**
   * Whether this principal ignores working hours entirely.
   *
   * `true` for automation. An always-on principal is active every hour of every
   * day, which means the off-hours feature must produce *nothing* for it —
   * see {@link offHoursFraction}.
   */
  alwaysOn: boolean;

  /**
   * Hour (UTC) at which an always-on principal runs a heavier batch, or `null`.
   *
   * This exists specifically to be a trap for the volume feature. The backup
   * role does six times its usual work at 02:00 UTC every night, so a detector
   * that flags volume spikes without accounting for recurrence reports the same
   * "anomaly" thirty times in thirty days.
   */
  batchHourUtc: number | null;

  /** The region this principal normally calls from. */
  homeRegion: string;

  /**
   * The first three octets of the principal's usual source address.
   *
   * A /24 rather than a single address because real people move between an
   * office, a VPN and a home connection without that being suspicious. The
   * new-geo signal is a call from a *different* prefix entirely.
   */
  homeIpPrefix: string;

  /** User agent strings this principal's tooling reports. */
  userAgents: string[];

  /** Mean number of events in an active hour. */
  eventsPerHourMean: number;

  /** Standard deviation of that count, giving each hour natural variance. */
  eventsPerHourStdDev: number;

  /**
   * Fraction of calls that fail with `AccessDenied` in normal operation.
   *
   * Non-zero on purpose. A baseline of exactly zero errors would make the
   * credential-abuse scenario trivially detectable by a single `if` statement,
   * which would flatter the model. Real accounts always have a low background
   * rate of permission errors from misconfigured tooling and stale scripts.
   */
  errorRate: number;

  /** The weighted action vocabulary this principal draws from. */
  actions: WeightedAction[];
}

/**
 * The six principals that populate the default generated account.
 *
 * Four humans with different schedules and jobs, and two pieces of automation.
 * The mix is intentional: the interesting failures of an anomaly detector all
 * happen at the boundaries between these populations.
 *
 * Exported so tests and the CLI can report on them, and so a future scenario
 * can be written against a specific persona by name.
 */
export const DEFAULT_PRINCIPALS: PrincipalProfile[] = [
  {
    arn: `arn:aws:iam::${ACCOUNT_ID}:user/alice-analyst`,
    principalId: "AIDAEXAMPLEALICE0001",
    type: "IAMUser",
    userName: "alice-analyst",
    description:
      "Data analyst, US Eastern hours. Reads S3 datasets; has never called IAM.",
    utcOffsetHours: -5,
    workStartHourLocal: 9,
    workEndHourLocal: 17,
    worksWeekends: false,
    alwaysOn: false,
    batchHourUtc: null,
    homeRegion: "us-east-1",
    homeIpPrefix: "192.0.2",
    userAgents: [
      "aws-cli/2.36.29 Python/3.12.4 Darwin/24.1.0",
      "Boto3/1.35.0 Python/3.12.4",
    ],
    eventsPerHourMean: 14,
    eventsPerHourStdDev: 5,
    errorRate: 0.01,
    actions: [...S3_READ_ACTIONS, ...CONSOLE_ACTIONS],
  },
  {
    arn: `arn:aws:iam::${ACCOUNT_ID}:user/bob-devops`,
    principalId: "AIDAEXAMPLEBOB00002",
    type: "IAMUser",
    userName: "bob-devops",
    description:
      "DevOps engineer, US Pacific hours. EC2 and CloudWatch; occasional weekend work.",
    utcOffsetHours: -8,
    workStartHourLocal: 8,
    workEndHourLocal: 18,
    worksWeekends: true,
    alwaysOn: false,
    batchHourUtc: null,
    homeRegion: "us-west-2",
    homeIpPrefix: "198.51.100",
    userAgents: [
      "aws-cli/2.36.29 Python/3.12.4 Linux/6.8.0",
      "terraform-provider-aws/5.70.0",
    ],
    eventsPerHourMean: 22,
    eventsPerHourStdDev: 8,
    errorRate: 0.02,
    actions: [...EC2_ACTIONS, ...CONSOLE_ACTIONS],
  },
  {
    arn: `arn:aws:iam::${ACCOUNT_ID}:user/carol-finance`,
    principalId: "AIDAEXAMPLECAROL003",
    type: "IAMUser",
    userName: "carol-finance",
    description:
      "Finance analyst, US Eastern hours. Low volume, console-heavy, strictly weekdays.",
    utcOffsetHours: -5,
    workStartHourLocal: 9,
    workEndHourLocal: 17,
    worksWeekends: false,
    alwaysOn: false,
    batchHourUtc: null,
    homeRegion: "us-east-1",
    homeIpPrefix: "192.0.2",
    userAgents: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AWS-Console"],
    eventsPerHourMean: 7,
    eventsPerHourStdDev: 3,
    errorRate: 0.01,
    actions: [...S3_READ_ACTIONS.slice(0, 2), ...CONSOLE_ACTIONS],
  },
  {
    // CONTROL. Sensitive IAM writes are this principal's ordinary job, so any
    // detector keyed on the action name alone will flag him constantly. He must
    // come out clean.
    arn: `arn:aws:iam::${ACCOUNT_ID}:user/dave-admin`,
    principalId: "AIDAEXAMPLEDAVE0004",
    type: "IAMUser",
    userName: "dave-admin",
    description:
      "CONTROL: platform administrator. Routine IAM writes are normal for him.",
    utcOffsetHours: -5,
    workStartHourLocal: 8,
    workEndHourLocal: 18,
    worksWeekends: false,
    alwaysOn: false,
    batchHourUtc: null,
    homeRegion: "us-east-1",
    homeIpPrefix: "192.0.2",
    userAgents: ["aws-cli/2.36.29 Python/3.12.4 Linux/6.8.0"],
    eventsPerHourMean: 11,
    eventsPerHourStdDev: 4,
    errorRate: 0.01,
    actions: [...IAM_ADMIN_ACTIONS, ...CONSOLE_ACTIONS],
  },
  {
    // CONTROL. Runs at 3am and makes hundreds of calls an hour, every night.
    // A detector keyed on "night-time" or "high volume" flags it thirty times
    // in thirty days. It must come out clean.
    arn: `arn:aws:iam::${ACCOUNT_ID}:role/cloudsentinel-backup-service`,
    principalId: "AROAEXAMPLEBACKUP005",
    type: "AssumedRole",
    sessionName: "backup-job",
    description:
      "CONTROL: automated backup role. Runs 24/7 with a heavy nightly batch at 02:00 UTC.",
    utcOffsetHours: 0,
    workStartHourLocal: 0,
    workEndHourLocal: 23,
    worksWeekends: true,
    alwaysOn: true,
    batchHourUtc: 2,
    homeRegion: "us-east-1",
    homeIpPrefix: "203.0.113",
    userAgents: ["aws-sdk-go/1.55.5 (go1.23; linux; amd64)"],
    eventsPerHourMean: 18,
    eventsPerHourStdDev: 4,
    errorRate: 0.005,
    actions: S3_WRITE_ACTIONS,
  },
  {
    arn: `arn:aws:iam::${ACCOUNT_ID}:role/cloudsentinel-ci-deployer`,
    principalId: "AROAEXAMPLECIDEP0006",
    type: "AssumedRole",
    sessionName: "github-actions",
    description:
      "CI deployment role. Bursty activity during the working day, quiet at night.",
    utcOffsetHours: 0,
    workStartHourLocal: 13,
    workEndHourLocal: 23,
    worksWeekends: false,
    alwaysOn: false,
    batchHourUtc: null,
    homeRegion: "us-east-1",
    homeIpPrefix: "203.0.113",
    userAgents: ["aws-sdk-js/3.1116.0 node/24.13.0"],
    eventsPerHourMean: 16,
    eventsPerHourStdDev: 9,
    errorRate: 0.015,
    actions: [...EC2_ACTIONS.slice(0, 5), ...S3_WRITE_ACTIONS.slice(0, 2)],
  },
];

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

/**
 * Builds a v4-shaped UUID from the seeded generator.
 *
 * `node:crypto`'s `randomUUID()` is not usable here: it draws from the system
 * entropy pool, so it would produce a different id on every run and destroy the
 * reproducibility the whole layer depends on. The version and variant nibbles
 * are set so the result is a well-formed v4 UUID, which matters only because a
 * malformed id in a fixture is the kind of thing that wastes an afternoon
 * later.
 *
 * SECURITY: predictable by construction, as with everything in
 * lib/util/random.ts. Never use this to mint an identifier that anything trusts.
 *
 * @param random - the generator to draw 16 bytes from.
 * @returns a lowercase, hyphenated UUID string.
 */
function uuid(random: Random): string {
  const bytes = Array.from({ length: 16 }, () => random.int(0, 255));

  // Version 4 in the high nibble of byte 6, RFC 4122 variant in byte 8.
  bytes[6] = (bytes[6]! & 0x0f) | 0x40;
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;

  const hex = bytes.map((b) => b.toString(16).padStart(2, "0")).join("");

  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20),
  ].join("-");
}

/**
 * Picks an action from a weighted list.
 *
 * Linear scan over the cumulative weight. With at most a dozen actions per
 * principal there is nothing to gain from a binary search, and the obvious
 * version is the one that can be checked by eye.
 *
 * @param random - the principal's generator.
 * @param actions - must not be empty.
 * @returns the selected action.
 * @throws {RangeError} if `actions` is empty, matching `Random.pick`.
 */
function pickWeighted(random: Random, actions: WeightedAction[]): WeightedAction {
  if (actions.length === 0) {
    throw new RangeError("pickWeighted: cannot pick from an empty action list");
  }

  const total = actions.reduce((sum, action) => sum + action.weight, 0);
  let threshold = random.next() * total;

  for (const action of actions) {
    threshold -= action.weight;
    if (threshold <= 0) return action;
  }

  // Floating-point rounding can leave a hair above zero on the last subtraction.
  return actions[actions.length - 1]!;
}

/**
 * Converts a UTC hour to the principal's local hour.
 *
 * @param utcHour - hour of day in UTC, 0-23.
 * @param offsetHours - the principal's offset from UTC.
 * @returns the local hour, wrapped into 0-23.
 */
function toLocalHour(utcHour: number, offsetHours: number): number {
  return ((utcHour + offsetHours) % 24 + 24) % 24;
}

/**
 * Decides whether a principal is active in a given hour, and how busy.
 *
 * @param profile - the principal.
 * @param timestamp - the start of the UTC hour under consideration.
 * @param random - the principal's generator.
 * @returns a multiplier on the principal's mean hourly rate. `0` means the
 *   principal produces no events this hour at all.
 */
function activityMultiplier(
  profile: PrincipalProfile,
  timestamp: Date,
  random: Random,
): number {
  const utcHour = timestamp.getUTCHours();

  if (profile.alwaysOn) {
    // Automation runs constantly, with a scheduled heavy window. The batch is a
    // fixed multiplier rather than a random one so it recurs identically every
    // night — a spike that is *predictable* is the thing the detector must
    // learn to ignore.
    return profile.batchHourUtc !== null && utcHour === profile.batchHourUtc
      ? 6
      : 1;
  }

  const dayOfWeek = timestamp.getUTCDay();
  const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;

  if (isWeekend && !profile.worksWeekends) {
    // Not zero. A human who never once touches the console at a weekend is a
    // cleaner signal than reality provides, and a detector tuned against that
    // would over-trust the day-of-week feature. Roughly one weekend hour in
    // twenty-five sees a little activity.
    return random.bool(0.04) ? 0.3 : 0;
  }

  const localHour = toLocalHour(utcHour, profile.utcOffsetHours);
  const withinWorkingHours =
    localHour >= profile.workStartHourLocal &&
    localHour <= profile.workEndHourLocal;

  if (withinWorkingHours) {
    // A midday hump: people are busiest in the middle of their day. Without
    // this the working day is a flat plateau, and the volume feature has less
    // natural variance to distinguish a real spike from.
    const middayDistance = Math.abs(
      localHour - (profile.workStartHourLocal + profile.workEndHourLocal) / 2,
    );
    return 1.25 - middayDistance * 0.06;
  }

  // Outside working hours but on a workday: the occasional late email or early
  // start. Again deliberately non-zero, for the same reason as the weekend case.
  return random.bool(0.07) ? 0.35 : 0;
}

// ---------------------------------------------------------------------------
// Event construction
// ---------------------------------------------------------------------------

/**
 * Fields a scenario may override when building an event.
 *
 * The attack generators below produce events that are structurally identical to
 * normal traffic and differ only in these dimensions — which is precisely the
 * situation a real detector faces. An attack event that carried some special
 * marker would make the whole exercise circular.
 */
interface EventOverrides {
  eventSource?: string;
  eventName?: string;
  readOnly?: boolean;
  eventCategory?: "Management" | "Data";
  awsRegion?: string;
  sourceIPAddress?: string;
  userAgent?: string;
  errorCode?: string;
  requestParameters?: Record<string, string | number | boolean> | null;
}

/**
 * Builds one event for a principal at a given instant.
 *
 * @param profile - whose event this is.
 * @param random - the principal's generator.
 * @param timestamp - exact event time.
 * @param overrides - scenario-specific field replacements. Anything omitted is
 *   drawn from the principal's normal profile.
 * @returns a complete {@link CloudTrailEvent}.
 */
function buildEvent(
  profile: PrincipalProfile,
  random: Random,
  timestamp: Date,
  overrides: EventOverrides = {},
): CloudTrailEvent {
  const action = pickWeighted(random, profile.actions);

  const failed =
    overrides.errorCode !== undefined || random.bool(profile.errorRate);

  const event: CloudTrailEvent = {
    eventVersion: EVENT_VERSION,
    eventID: uuid(random),
    eventTime: timestamp.toISOString(),
    eventSource: overrides.eventSource ?? action.eventSource,
    eventName: overrides.eventName ?? action.eventName,
    awsRegion: overrides.awsRegion ?? profile.homeRegion,
    sourceIPAddress:
      overrides.sourceIPAddress ??
      `${profile.homeIpPrefix}.${random.int(1, 254)}`,
    userAgent: overrides.userAgent ?? random.pick(profile.userAgents),
    readOnly: overrides.readOnly ?? action.readOnly,
    eventCategory: overrides.eventCategory ?? action.eventCategory,
    userIdentity: {
      type: profile.type,
      principalId: profile.principalId,
      arn: profile.arn,
      accountId: ACCOUNT_ID,
      ...(profile.userName ? { userName: profile.userName } : {}),
      ...(profile.sessionName ? { sessionName: profile.sessionName } : {}),
    },
    requestParameters:
      overrides.requestParameters !== undefined
        ? overrides.requestParameters
        : (action.parameters?.(random) ?? null),
  };

  if (failed) {
    event.errorCode = overrides.errorCode ?? "AccessDenied";
    event.errorMessage = `User: ${profile.arn} is not authorized to perform: ${event.eventSource.split(".")[0]}:${event.eventName}`;
  }

  return event;
}

// ---------------------------------------------------------------------------
// Baseline traffic
// ---------------------------------------------------------------------------

/**
 * Generates a principal's ordinary activity across the whole window.
 *
 * Walks every hour of every day and asks {@link activityMultiplier} how busy
 * this principal is, then draws that many events at random moments inside the
 * hour.
 *
 * @param profile - the principal to generate for.
 * @param random - a generator dedicated to this principal.
 * @param startTime - first instant of the window.
 * @param days - length of the window.
 * @returns the principal's events, in no particular order — the caller sorts.
 */
function generateBaseline(
  profile: PrincipalProfile,
  random: Random,
  startTime: Date,
  days: number,
): CloudTrailEvent[] {
  const events: CloudTrailEvent[] = [];
  const totalHours = days * 24;

  for (let hour = 0; hour < totalHours; hour += 1) {
    const hourStart = new Date(startTime.getTime() + hour * HOUR_MS);
    const multiplier = activityMultiplier(profile, hourStart, random);

    if (multiplier <= 0) continue;

    const count = Math.max(
      0,
      Math.round(
        random.normal(
          profile.eventsPerHourMean * multiplier,
          profile.eventsPerHourStdDev,
        ),
      ),
    );

    for (let index = 0; index < count; index += 1) {
      // Uniform within the hour. Real calls arrive in bursts, but bursts inside
      // a one-hour bucket are invisible to hourly features, so modelling them
      // would add generator complexity that no downstream feature can see.
      const offsetMs = random.int(0, HOUR_MS - 1);
      events.push(
        buildEvent(profile, random, new Date(hourStart.getTime() + offsetMs)),
      );
    }
  }

  return events;
}

// ---------------------------------------------------------------------------
// Attack scenarios
// ---------------------------------------------------------------------------

/**
 * One injected attack: the events it produced and the label describing it.
 */
interface InjectedAttack {
  events: CloudTrailEvent[];
  label: AnomalyLabel;
}

/**
 * Builds the label for a set of attack events.
 *
 * Factored out because every scenario needs the same start/end/id bookkeeping,
 * and getting it subtly wrong in one scenario would quietly corrupt the
 * evaluation for that scenario only — the hardest kind of bug to notice in a
 * metrics table.
 *
 * @param scenario - which technique was injected.
 * @param profile - the principal it was performed as.
 * @param events - the attack's events. Must not be empty.
 * @param description - a one-line human-readable summary.
 * @returns the completed label.
 * @throws {RangeError} if `events` is empty, which would mean a scenario
 *   silently generated nothing and would show up as an unexplained recall miss.
 */
function labelFor(
  scenario: AnomalyLabel["scenario"],
  profile: PrincipalProfile,
  events: CloudTrailEvent[],
  description: string,
): AnomalyLabel {
  if (events.length === 0) {
    throw new RangeError(`labelFor: scenario ${scenario} produced no events`);
  }

  const times = events.map((event) => event.eventTime).sort();

  return {
    scenario,
    principalArn: profile.arn,
    startTime: times[0]!,
    endTime: times[times.length - 1]!,
    eventIds: events.map((event) => event.eventID),
    description,
  };
}

/**
 * Privilege escalation: a principal with no IAM history starts rewriting its
 * own permissions.
 *
 * The sequence is the recognisable one — look at yourself, look at your
 * policies, then grant yourself more and mint a key to keep the access. Placed
 * outside working hours, but the hour is *not* the intended signal: the signal
 * is that `alice-analyst` has made zero IAM calls in the preceding weeks and
 * then makes nine in eleven minutes.
 *
 * @param profile - the victim principal.
 * @param random - the principal's generator.
 * @param at - when the sequence begins.
 * @returns the injected events and their label.
 */
function injectPrivilegeEscalation(
  profile: PrincipalProfile,
  random: Random,
  at: Date,
): InjectedAttack {
  const sequence: Array<[string, string, boolean, Record<string, string>]> = [
    ["sts.amazonaws.com", "GetCallerIdentity", true, {}],
    ["iam.amazonaws.com", "GetUser", true, { userName: "alice-analyst" }],
    [
      "iam.amazonaws.com",
      "ListAttachedUserPolicies",
      true,
      { userName: "alice-analyst" },
    ],
    ["iam.amazonaws.com", "ListUserPolicies", true, { userName: "alice-analyst" }],
    [
      "iam.amazonaws.com",
      "CreatePolicyVersion",
      false,
      {
        policyArn: `arn:aws:iam::${ACCOUNT_ID}:policy/analyst-readonly`,
        setAsDefault: "true",
      },
    ],
    [
      "iam.amazonaws.com",
      "AttachUserPolicy",
      false,
      {
        userName: "alice-analyst",
        policyArn: "arn:aws:iam::aws:policy/AdministratorAccess",
      },
    ],
    [
      "iam.amazonaws.com",
      "PutUserPolicy",
      false,
      { userName: "alice-analyst", policyName: "inline-escalation" },
    ],
    ["iam.amazonaws.com", "CreateAccessKey", false, { userName: "alice-analyst" }],
    ["iam.amazonaws.com", "ListUsers", true, {}],
  ];

  // A single stolen session: one address for the whole sequence.
  const sourceIp = `${profile.homeIpPrefix}.${random.int(1, 254)}`;
  let cursor = at.getTime();
  const events: CloudTrailEvent[] = [];

  for (const [eventSource, eventName, readOnly, parameters] of sequence) {
    events.push(
      buildEvent(profile, random, new Date(cursor), {
        eventSource,
        eventName,
        readOnly,
        eventCategory: "Management",
        sourceIPAddress: sourceIp,
        requestParameters: Object.keys(parameters).length > 0 ? parameters : null,
      }),
    );
    // Tens of seconds apart: fast enough to be one session, slow enough to look
    // like a person typing rather than a script.
    cursor += random.int(20_000, 110_000);
  }

  return {
    events,
    label: labelFor(
      "privilege_escalation",
      profile,
      events,
      `${events.length} IAM calls in ${Math.round((cursor - at.getTime()) / 60_000)} minutes by a principal with no prior IAM activity, ending in AttachUserPolicy(AdministratorAccess) and CreateAccessKey`,
    ),
  };
}

/**
 * Off-hours access: entirely ordinary work, done in the middle of the night.
 *
 * Deliberately the weakest scenario in the set. Every event uses the
 * principal's normal actions, normal address and normal region; the only thing
 * wrong is the clock. It is included to test whether the model can act on a
 * single weak feature, and it is genuinely acceptable for a detector to rank
 * this lowest — that result is reported honestly by ml/evaluate.py rather than
 * tuned away.
 *
 * @param profile - the principal.
 * @param random - the principal's generator.
 * @param at - when the session begins, in UTC.
 * @returns the injected events and their label.
 */
function injectOffHoursAccess(
  profile: PrincipalProfile,
  random: Random,
  at: Date,
): InjectedAttack {
  const events: CloudTrailEvent[] = [];
  const durationMinutes = random.int(70, 110);
  const count = random.int(26, 38);

  for (let index = 0; index < count; index += 1) {
    const offsetMs = random.int(0, durationMinutes * 60_000);
    events.push(buildEvent(profile, random, new Date(at.getTime() + offsetMs)));
  }

  const localHour = toLocalHour(at.getUTCHours(), profile.utcOffsetHours);

  return {
    events,
    label: labelFor(
      "off_hours_access",
      profile,
      events,
      `${count} routine calls beginning at ${String(localHour).padStart(2, "0")}:00 local time, well outside this principal's ${profile.workStartHourLocal}:00-${profile.workEndHourLocal}:00 pattern`,
    ),
  };
}

/**
 * New-geo login: a console sign-in from a region and address range this
 * principal has never used, followed by exploratory calls.
 *
 * The classic "impossible travel" alert. Two features move at once here — an
 * unseen region and an unseen IP prefix — which makes it the scenario a
 * detector is most likely to catch, and a useful upper bound on what the
 * pipeline can do.
 *
 * @param profile - the principal.
 * @param random - the principal's generator.
 * @param at - when the login happens.
 * @returns the injected events and their label.
 */
function injectNewGeoLogin(
  profile: PrincipalProfile,
  random: Random,
  at: Date,
): InjectedAttack {
  // A prefix and region the profile never uses. Hard-coded rather than derived
  // so the scenario cannot accidentally pick the principal's own home range if
  // the profiles are later edited.
  const foreignIp = `203.0.113.${random.int(1, 254)}`;
  const foreignRegion = "eu-west-1";

  const events: CloudTrailEvent[] = [
    buildEvent(profile, random, at, {
      eventSource: "signin.amazonaws.com",
      eventName: "ConsoleLogin",
      readOnly: false,
      eventCategory: "Management",
      awsRegion: foreignRegion,
      sourceIPAddress: foreignIp,
      userAgent: "Mozilla/5.0 (X11; Linux x86_64) AWS-Console",
      requestParameters: { mfaUsed: "No" },
    }),
  ];

  let cursor = at.getTime() + random.int(30_000, 90_000);
  const followUpCount = random.int(14, 20);

  for (let index = 0; index < followUpCount; index += 1) {
    events.push(
      buildEvent(profile, random, new Date(cursor), {
        awsRegion: foreignRegion,
        sourceIPAddress: foreignIp,
        userAgent: "Mozilla/5.0 (X11; Linux x86_64) AWS-Console",
      }),
    );
    cursor += random.int(15_000, 70_000);
  }

  return {
    events,
    label: labelFor(
      "new_geo_login",
      profile,
      events,
      `ConsoleLogin without MFA from ${foreignIp} in ${foreignRegion}, a region and address range never previously used by this principal, followed by ${followUpCount} calls`,
    ),
  };
}

/**
 * Credential abuse: someone finding out what a stolen key can reach.
 *
 * A burst of calls across services the principal never touches, most of which
 * fail with `AccessDenied`. This is what permission enumeration looks like from
 * the log's side, and the error rate is the signal — an attacker with a stolen
 * credential does not know its scope, so they discover it by trying, whereas a
 * legitimate user's tooling was built around permissions they already have.
 *
 * @param profile - the principal whose credential was abused.
 * @param random - the principal's generator.
 * @param at - when the burst begins.
 * @returns the injected events and their label.
 */
function injectCredentialAbuse(
  profile: PrincipalProfile,
  random: Random,
  at: Date,
): InjectedAttack {
  const probes: Array<[string, string]> = [
    ["iam.amazonaws.com", "ListUsers"],
    ["iam.amazonaws.com", "ListRoles"],
    ["iam.amazonaws.com", "ListAccessKeys"],
    ["iam.amazonaws.com", "GetAccountSummary"],
    ["iam.amazonaws.com", "ListAttachedUserPolicies"],
    ["ec2.amazonaws.com", "DescribeInstances"],
    ["ec2.amazonaws.com", "DescribeSecurityGroups"],
    ["ec2.amazonaws.com", "DescribeVpcs"],
    ["s3.amazonaws.com", "ListBuckets"],
    ["s3.amazonaws.com", "GetBucketPolicy"],
    ["kms.amazonaws.com", "ListKeys"],
    ["lambda.amazonaws.com", "ListFunctions"],
    ["rds.amazonaws.com", "DescribeDBInstances"],
    ["secretsmanager.amazonaws.com", "ListSecrets"],
    ["dynamodb.amazonaws.com", "ListTables"],
    ["sts.amazonaws.com", "GetCallerIdentity"],
  ];

  const sourceIp = `203.0.113.${random.int(1, 254)}`;
  const count = random.int(28, 40);
  let cursor = at.getTime();
  const events: CloudTrailEvent[] = [];
  let denied = 0;

  for (let index = 0; index < count; index += 1) {
    const [eventSource, eventName] = random.pick(probes);
    // Most probes fail — that is the whole point of probing. `GetCallerIdentity`
    // is the exception every credential can call, which is why it is usually
    // the attacker's first move.
    const fails = eventName !== "GetCallerIdentity" && random.bool(0.82);
    if (fails) denied += 1;

    events.push(
      buildEvent(profile, random, new Date(cursor), {
        eventSource,
        eventName,
        readOnly: true,
        eventCategory: "Management",
        sourceIPAddress: sourceIp,
        requestParameters: null,
        ...(fails ? { errorCode: "AccessDenied" } : {}),
      }),
    );

    // Scripted, so much faster than a human clicking around.
    cursor += random.int(1_500, 12_000);
  }

  return {
    events,
    label: labelFor(
      "credential_abuse",
      profile,
      events,
      `${count} enumeration calls across ${new Set(probes.map(([source]) => source)).size} services from ${sourceIp}, ${denied} of them denied — permission discovery with a stolen credential`,
    ),
  };
}

/**
 * Data exfiltration: a read-volume spike far beyond the principal's baseline.
 *
 * Runs during working hours, from the principal's usual address, using an
 * action the principal calls all day. Nothing about any individual event is
 * suspicious; only the rate and the breadth of objects touched are. This is the
 * scenario that most clearly justifies per-principal baselining — 300
 * `GetObject` calls in half an hour is a crisis for an analyst and a quiet
 * afternoon for a backup job.
 *
 * @param profile - the principal.
 * @param random - the principal's generator.
 * @param at - when the spike begins.
 * @returns the injected events and their label.
 */
function injectDataExfiltration(
  profile: PrincipalProfile,
  random: Random,
  at: Date,
): InjectedAttack {
  const events: CloudTrailEvent[] = [];
  const count = random.int(260, 340);
  const durationMs = random.int(20, 32) * 60_000;
  const sourceIp = `${profile.homeIpPrefix}.${random.int(1, 254)}`;

  for (let index = 0; index < count; index += 1) {
    events.push(
      buildEvent(profile, random, new Date(at.getTime() + random.int(0, durationMs)), {
        eventSource: "s3.amazonaws.com",
        eventName: "GetObject",
        readOnly: true,
        eventCategory: "Data",
        sourceIPAddress: sourceIp,
        userAgent: "aws-cli/2.36.29 Python/3.12.4 Darwin/24.1.0",
        requestParameters: {
          bucketName: "cloudsentinel-analytics",
          // A distinct key every time: this is a sweep of the bucket, not a
          // retry loop, and the distinct-resource count is what separates them.
          key: `datasets/${random.int(2019, 2026)}/part-${index}-${random.int(1000, 9999)}.parquet`,
        },
      }),
    );
  }

  return {
    events,
    label: labelFor(
      "data_exfiltration",
      profile,
      events,
      `${count} GetObject calls in ${Math.round(durationMs / 60_000)} minutes against ${count} distinct keys, roughly ${Math.round(count / (durationMs / HOUR_MS) / profile.eventsPerHourMean)}x this principal's normal hourly rate`,
    ),
  };
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

/** Options for {@link generateActivity}. All have defaults. */
export interface GenerateOptions {
  /** PRNG seed. The same seed always produces byte-identical output. */
  seed?: string;

  /** Length of the generated window in days. Must be at least 1. */
  days?: number;

  /** ISO 8601 UTC timestamp for the start of the window. */
  startTime?: string;

  /** Principals to generate for. Defaults to {@link DEFAULT_PRINCIPALS}. */
  principals?: PrincipalProfile[];

  /**
   * Whether to inject the labelled attacks.
   *
   * `false` produces clean baseline traffic with an empty label set. That mode
   * exists to answer a question the attack-laden log cannot: how many
   * *false* positives does the detector produce on a month of ordinary work?
   * A model can score well on recall and still be unusable if it flags the
   * backup job every night, and only a clean run measures that.
   */
  injectAttacks?: boolean;
}

/** What {@link generateActivity} returns: the log and its separate answer key. */
export interface GeneratedActivity {
  /** The events, with no labels. This is all the detector ever sees. */
  log: ActivityLog;

  /** The answer key, read only by the evaluation step. */
  labels: ActivityLabels;
}

/**
 * Generates a full synthetic activity log with labelled attacks hidden in it.
 *
 * Each principal is given its own generator, seeded from the run seed plus its
 * ARN. That is a deliberate structural choice: it means adding, removing or
 * reordering a principal changes only that principal's events, leaving everyone
 * else's stream untouched. With one shared generator, inserting a principal
 * would shift every subsequent draw and rewrite the entire log — making any
 * change to the roster produce an unreviewable diff and invalidating any
 * threshold tuned against the previous data.
 *
 * The attacks are scheduled in the second half of the window so that each
 * victim has weeks of established normal behaviour behind it. That ordering is
 * not cosmetic: the detector baselines a principal against its own history, so
 * an attack on day 2 would be measured against almost no history and would be
 * unfairly hard to catch.
 *
 * @param options - see {@link GenerateOptions}.
 * @returns the log and the labels, both sorted by time.
 * @throws {RangeError} if `days` is less than 1, if `startTime` is not a valid
 *   date, or if `principals` is empty — each of which would otherwise produce a
 *   silently empty log that looks like a detector failure much later.
 */
export function generateActivity(
  options: GenerateOptions = {},
): GeneratedActivity {
  const seed = options.seed ?? DEFAULT_SEED;
  const days = options.days ?? DEFAULT_DAYS;
  const principals = options.principals ?? DEFAULT_PRINCIPALS;
  const injectAttacks = options.injectAttacks ?? true;

  if (days < 1) {
    throw new RangeError(`generateActivity: days must be >= 1, got ${days}`);
  }
  if (principals.length === 0) {
    throw new RangeError("generateActivity: at least one principal is required");
  }

  const startTime = new Date(options.startTime ?? DEFAULT_START_TIME);
  if (Number.isNaN(startTime.getTime())) {
    throw new RangeError(
      `generateActivity: startTime is not a valid date: ${options.startTime}`,
    );
  }

  const events: CloudTrailEvent[] = [];
  const labels: AnomalyLabel[] = [];

  // --- Baseline ----------------------------------------------------------

  const generators = new Map<string, Random>();

  for (const profile of principals) {
    const random = createRandom(`${seed}:${profile.arn}`);
    generators.set(profile.arn, random);
    events.push(...generateBaseline(profile, random, startTime, days));
  }

  // --- Attacks -----------------------------------------------------------

  if (injectAttacks) {
    /**
     * Places an attack at a given day and UTC hour of the window.
     *
     * Scheduled by fraction of the window rather than an absolute day so that
     * `--days 7` and `--days 30` both produce a sensible spread with all five
     * scenarios present, instead of silently dropping the later ones off the
     * end of a short run.
     */
    const at = (fraction: number, utcHour: number, minute: number): Date => {
      const day = Math.min(days - 1, Math.floor(days * fraction));
      return new Date(
        startTime.getTime() + day * DAY_MS + utcHour * HOUR_MS + minute * 60_000,
      );
    };

    const byName = (name: string): PrincipalProfile => {
      const found = principals.find((profile) => profile.arn.endsWith(name));
      if (!found) {
        throw new RangeError(
          `generateActivity: no principal matching ${name}; a custom principal list must still include the attack victims, or pass injectAttacks: false`,
        );
      }
      return found;
    };

    const alice = byName("alice-analyst");
    const bob = byName("bob-devops");
    const carol = byName("carol-finance");

    const scheduled: InjectedAttack[] = [
      // 14:10 UTC = mid-morning for Carol. During her working hours on purpose:
      // the error burst has to carry this one on its own.
      injectCredentialAbuse(carol, generators.get(carol.arn)!, at(0.4, 14, 10)),
      // 03:20 UTC = 22:20 the previous evening for Alice.
      injectPrivilegeEscalation(
        alice,
        generators.get(alice.arn)!,
        at(0.5, 3, 20),
      ),
      // 02:00 UTC = 18:00 Pacific — evening for Bob, so the hour is unremarkable
      // and the geography is the signal.
      injectNewGeoLogin(bob, generators.get(bob.arn)!, at(0.6, 2, 0)),
      // 05:30 UTC = 00:30 for Carol. Nothing but the clock is wrong.
      injectOffHoursAccess(carol, generators.get(carol.arn)!, at(0.7, 5, 30)),
      // 16:00 UTC = 11:00 for Alice, squarely inside her working day.
      injectDataExfiltration(alice, generators.get(alice.arn)!, at(0.8, 16, 0)),
    ];

    for (const attack of scheduled) {
      events.push(...attack.events);
      labels.push(attack.label);
    }
  }

  // --- Assembly ----------------------------------------------------------

  // Sorted by time, with the event id as a tie-break. The tie-break matters:
  // two events in the same millisecond would otherwise order differently
  // between Node versions, and a fixture that reshuffles on regeneration cannot
  // be diffed.
  events.sort((a, b) =>
    a.eventTime === b.eventTime
      ? a.eventID.localeCompare(b.eventID)
      : a.eventTime.localeCompare(b.eventTime),
  );

  labels.sort((a, b) => a.startTime.localeCompare(b.startTime));

  const metadata: ActivityLogMetadata = {
    seed,
    startTime: startTime.toISOString(),
    days,
    eventCount: events.length,
    principalCount: principals.length,
    // Derived from the window, not from the clock — see the field's doc comment
    // in lib/types/cloudtrail.ts for why a real timestamp here would break the
    // determinism check.
    generatedAt: new Date(startTime.getTime() + days * DAY_MS).toISOString(),
  };

  return {
    log: { metadata, events },
    labels: { metadata, labels },
  };
}
